name: myquitmate
description: A smoking cessation prototype app (Flutter)
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  provider: ^6.0.5
  share_plus: ^7.2.2   # <<< tambah ini
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
